---
branches:
  only:
  - master
language: ruby
bundler_args: --without development
script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.5
env:
  matrix:
    - PUPPET_VERSION="~> 2.7.0" FACTER_VERSION="~> 1.6.0"
    - PUPPET_VERSION="~> 2.7.0" FACTER_VERSION="~> 1.7.0"
    - PUPPET_VERSION="~> 3.0"
matrix:
  exclude:
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 2.7.0" FACTER_VERSION="~> 1.6.0"
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 2.7.0" FACTER_VERSION="~> 1.7.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 2.7.0" FACTER_VERSION="~> 1.6.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 2.7.0" FACTER_VERSION="~> 1.7.0"
    - rvm: 2.1.5
      env: PUPPET_VERSION="~> 2.7.0" FACTER_VERSION="~> 1.6.0"
    - rvm: 2.1.5
      env: PUPPET_VERSION="~> 2.7.0" FACTER_VERSION="~> 1.7.0"
notifications:
  email: false
